// The agent client seam. The genie capability calls the REAL backend
// (/api/genie/ask); RAG and workflow are convincing prototype mocks (matching
// the original app's mocked-backend status). All three stream via the same
// AgentEvent generator so a future fully-live adapter is a drop-in swap.

import type {
  AgentEvent, Capability, GenieSpaceId, WorkflowId, WorkflowParam,
  WorkflowStep, WorkflowArtifact, Citation, ChartSpec, ColumnDef, Row,
} from "./types";
import { GENIE_SPACE_LABELS } from "./types";
import { askGenie, type Module } from "../api/client";

export type ForcedRoute = Capability | GenieSpaceId;

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
const between = (a: number, b: number) => a + Math.floor(Math.random() * (b - a));
const tokenize = (t: string) => t.match(/\S+\s*/g) ?? [t];

let _seq = 0;
const runRequestId = () => `rr-${Date.now().toString(36)}-${(_seq += 1)}`;

// Map the three chatbot Genie spaces onto our real module Genie spaces.
const SPACE_TO_MODULE: Record<GenieSpaceId, Module> = {
  members: "health",
  partners: "finance",
  financials: "bridge",
};

// ── Lightweight intent router ─────────────────────────────────────────────
type Decision =
  | { kind: "genie"; space: GenieSpaceId }
  | { kind: "rag" }
  | { kind: "workflow"; workflowId: WorkflowId }
  | { kind: "clarify"; question: string; chips: string[] };

function route(text: string, forced?: ForcedRoute): Decision {
  const t = text.toLowerCase();
  if (forced === "genie" || forced === "rag" || forced === "workflow") {
    if (forced === "rag") return { kind: "rag" };
    if (forced === "workflow") return { kind: "workflow", workflowId: pickWorkflow(t) };
    return { kind: "genie", space: "members" };
  }
  if (forced === "members" || forced === "partners" || forced === "financials")
    return { kind: "genie", space: forced };

  // Workflow intent
  if (/\b(report|draft|compile|email|send|submit|review)\b/.test(t) && /\b(report|review|send|email|compile)\b/.test(t))
    return { kind: "workflow", workflowId: pickWorkflow(t) };
  // RAG intent — policy/contract/clinical questions
  if (/\b(rule|rules|clause|policy|cap|contract|schedule|points|termination|exclusivity|compliance|popia|fsca)\b/.test(t))
    return { kind: "rag" };
  // Genie space by keyword
  if (/\b(partner|virgin|planet|check-?in|utilis|redemption|cap)\b/.test(t)) return { kind: "genie", space: "partners" };
  if (/\b(claim|premium|loss ratio|net value|lapse|actuar)\b/.test(t)) return { kind: "genie", space: "financials" };
  if (/\b(gym|step|screening|engagement|active|member|tier|goal)\b/.test(t)) return { kind: "genie", space: "members" };
  // Default to analytics on the member space
  return { kind: "genie", space: "members" };
}

const pickWorkflow = (t: string): WorkflowId =>
  /\b(anomaly|adjustment|actuar|cashback)\b/.test(t) ? "submit_reward_adjustment_review" : "generate_partner_performance_report";

// ── Build a genie_result block from the REAL backend response ─────────────
function buildGenieBlock(space: GenieSpaceId, ans: { text: string; table: { columns: string[]; rows: unknown[][] } | null }) {
  const cols: ColumnDef[] = (ans.table?.columns ?? []).map((c) => ({
    key: c, label: c.replace(/_/g, " "),
    numeric: /(_zar|_pct|count|members|rate|ratio|value|payout|premium|claims|net)/i.test(c),
    format: /_zar|payout|premium|claims|net|value/i.test(c) ? "zar" : /_pct|rate|ratio/i.test(c) ? "percent" : "number",
  }));
  const rows: Row[] = (ans.table?.rows ?? []).map((r) => {
    const o: Row = {};
    cols.forEach((c, i) => {
      const v = (r as unknown[])[i];
      o[c.key] = c.numeric ? Number(v) : (v as string | null);
    });
    return o;
  });
  // Derive a simple chart spec: first string col = x, first numeric col = series.
  const xCol = cols.find((c) => !c.numeric);
  const yCols = cols.filter((c) => c.numeric).slice(0, 3);
  const chartSpec: ChartSpec | null = xCol && yCols.length && rows.length > 1 && rows.length <= 40
    ? { kind: "bar", xKey: xCol.key, series: yCols.map((c) => ({ key: c.key, label: c.label })), yFormat: yCols[0].format ?? "number" }
    : null;
  return {
    type: "genie_result" as const,
    summary: ans.text,
    chartSpec,
    table: { columns: cols, rows },
    sql: "-- Generated by Genie against the governed gold tables.\n-- (full SQL available in the Databricks Genie space)",
    spaceName: GENIE_SPACE_LABELS[space],
    rowCount: rows.length,
    executionMs: 0,
    asOf: new Date().toISOString().slice(0, 10),
  };
}

export class AgentClient {
  private cancelled = new Set<string>();
  private convGenie = new Map<string, string>(); // conversationId -> genie conversation_id

  cancel(id: string) { this.cancelled.add(id); }
  private live(id: string) { return !this.cancelled.has(id); }

  async *sendMessage(cid: string, text: string, forced?: ForcedRoute): AsyncGenerator<AgentEvent> {
    this.cancelled.delete(cid);
    const d = route(text, forced);
    await sleep(between(200, 450));
    if (!this.live(cid)) return;

    if (d.kind === "genie") yield* this.genieFlow(cid, d.space, text);
    else if (d.kind === "rag") yield* this.ragFlow(cid, text);
    else if (d.kind === "workflow") yield* this.workflowPlanFlow(cid, d.workflowId);
    else yield* this.clarifyFlow(cid, d);

    if (this.live(cid)) yield { kind: "done" };
  }

  private async *genieFlow(cid: string, space: GenieSpaceId, text: string): AsyncGenerator<AgentEvent> {
    yield { kind: "block_start", block: { type: "status", label: `Querying ${GENIE_SPACE_LABELS[space]}…`, capability: "genie" } };
    let ans;
    try {
      ans = await askGenie(SPACE_TO_MODULE[space], text, this.convGenie.get(cid) ?? null);
      if (ans.conversation_id) this.convGenie.set(cid, ans.conversation_id);
    } catch {
      ans = null;
    }
    if (!this.live(cid)) return;
    if (!ans || ans.error) {
      yield { kind: "block_start", block: { type: "error", title: "Genie couldn't answer that", detail: "Try narrowing the question or rephrasing, then run it again.", retryable: true } };
      yield { kind: "block_end" };
      return;
    }
    const block = buildGenieBlock(space, ans);
    // Stream the summary as prose first
    yield { kind: "block_start", block: { type: "text", markdown: "" } };
    for (const tok of tokenize(block.summary)) {
      if (!this.live(cid)) return;
      yield { kind: "block_delta", delta: tok };
      await sleep(between(8, 22));
    }
    yield { kind: "block_end" };
    // Then the result card (summary cleared so header doesn't duplicate it)
    yield { kind: "block_start", block: { ...block, summary: "" } };
    yield { kind: "block_end", block: { ...block, summary: "" } };
    yield* this.followups(cid, ["Break this down further", "Turn this into a report", "Show a related policy rule"]);
  }

  private async *ragFlow(cid: string, question: string): AsyncGenerator<AgentEvent> {
    yield { kind: "block_start", block: { type: "status", label: "Searching policy documents…", capability: "rag" } };
    // Real RAG over the Vector Search policy index.
    let data: { markdown: string; citations: Citation[]; source?: string; lowConfidence?: boolean } | null = null;
    try {
      const res = await fetch("/api/genie/rag", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question }),
      });
      if (res.ok) data = await res.json();
    } catch { /* fall through */ }
    if (!this.live(cid)) return;
    if (!data || data.source === "error") {
      yield { kind: "block_start", block: { type: "error", title: "Document search unavailable", detail: "The policy library couldn't be reached — please try again.", retryable: true } };
      yield { kind: "block_end" };
      return;
    }
    yield { kind: "block_start", block: { type: "citation_answer", markdown: "", citations: data.citations, lowConfidence: data.lowConfidence } };
    for (const tok of tokenize(data.markdown)) {
      if (!this.live(cid)) return;
      yield { kind: "block_delta", delta: tok };
      await sleep(between(8, 18));
    }
    yield { kind: "block_end", block: { type: "citation_answer", markdown: data.markdown, citations: data.citations, lowConfidence: data.lowConfidence } };
    yield* this.followups(cid, ["Show the source passage", "Which document governs this?"]);
  }

  private async *workflowPlanFlow(cid: string, workflowId: WorkflowId): AsyncGenerator<AgentEvent> {
    yield { kind: "block_start", block: { type: "status", label: "Preparing workflow plan…", capability: "workflow" } };
    await sleep(between(600, 1200));
    if (!this.live(cid)) return;
    const plan = WORKFLOW_PLANS[workflowId];
    yield { kind: "block_start", block: { type: "workflow_plan", workflowId, runRequestId: runRequestId(), ...plan } };
    yield { kind: "block_end" };
  }

  private async *clarifyFlow(cid: string, d: Extract<Decision, { kind: "clarify" }>): AsyncGenerator<AgentEvent> {
    yield { kind: "block_start", block: { type: "text", markdown: "" } };
    for (const tok of tokenize(d.question)) {
      if (!this.live(cid)) return;
      yield { kind: "block_delta", delta: tok };
      await sleep(between(15, 30));
    }
    yield { kind: "block_end" };
    yield* this.followups(cid, d.chips);
  }

  private async *followups(cid: string, suggestions: string[]): AsyncGenerator<AgentEvent> {
    if (!this.live(cid)) return;
    yield { kind: "block_start", block: { type: "followups", suggestions } };
    yield { kind: "block_end" };
  }

  async *confirmWorkflow(_rr: string, params: WorkflowParam[]): AsyncGenerator<AgentEvent> {
    const workflowId: WorkflowId = params.some((p) => p.key === "anomaly_scope")
      ? "submit_reward_adjustment_review" : "generate_partner_performance_report";
    const run = WORKFLOW_RUNS[workflowId];
    const steps: WorkflowStep[] = run.steps.map((s) => ({ label: s.label, state: "pending" as const }));
    const artifacts: WorkflowArtifact[] = [];
    let runId = run.runId;

    // The partner-report workflow triggers a REAL Databricks Job run.
    if (workflowId === "generate_partner_performance_report") {
      const partner = params.find((p) => p.key === "partner")?.value ?? "Planet Fitness";
      const period = params.find((p) => p.key === "period")?.value ?? "Q3 2026";
      try {
        const res = await fetch("/api/workflow/partner-report", {
          method: "POST", headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ partner, period }),
        });
        const data = await res.json();
        if (data.run_id) {
          runId = `job-run ${data.run_id}`;
          // Point the artifact at a real CSV download of the report the Job wrote.
          const dl = `/api/workflow/report?partner=${encodeURIComponent(partner)}&period=${encodeURIComponent(period)}`;
          run.artifacts[0] = { ...run.artifacts[0], url: dl };
        }
      } catch { /* fall back to simulated run */ }
    }

    const emit = (done = false): Extract<AgentEvent, { kind: "block_start" }> => ({
      kind: "block_start",
      block: { type: "workflow_progress", runId, workflowId, steps: steps.map((s) => ({ ...s })), artifacts: [...artifacts], executedBy: "Pieter van der Merwe", executedAt: new Date().toISOString(), done },
    });
    yield emit();
    for (let i = 0; i < run.steps.length; i++) {
      steps[i].state = "running"; yield emit();
      await sleep(run.steps[i].ms);
      if (run.steps[i].retry) {
        steps[i].state = "failed"; steps[i].detail = "Transient error. Retrying step…"; yield emit();
        await sleep(between(900, 1400)); steps[i].state = "running"; steps[i].detail = undefined; yield emit();
        await sleep(between(1000, 1500));
      }
      steps[i].state = "done"; yield emit();
    }
    artifacts.push(...run.artifacts);
    const final = emit(true);
    yield final;
    yield { kind: "block_end", block: final.block };
    yield { kind: "done" };
  }
}

let _client: AgentClient | null = null;
export function getAgentClient(): AgentClient {
  return (_client ??= new AgentClient());
}

// ── Prototype fixtures (workflow defs — RAG is now real Vector Search) ─────
interface PlanDef { title: string; params: WorkflowParam[]; steps: string[]; consequence: string; recipients?: string[]; requiresTypedConfirmation?: boolean; }
const WORKFLOW_PLANS: Record<WorkflowId, PlanDef> = {
  generate_partner_performance_report: {
    title: "Q3 2026 performance report — Planet Fitness",
    params: [
      { key: "partner", label: "Partner", value: "Planet Fitness", editable: true, kind: "text" },
      { key: "period", label: "Period", value: "Q3 2026", editable: true, kind: "text" },
      { key: "recipient_group", label: "Recipients", value: "Partnerships Team (4)", editable: true, kind: "enum", options: ["Partnerships Team (4)", "Wellness Ops (6)", "Exco (read-only) (3)"] },
      { key: "include_commercials", label: "Include commercial terms", value: "Yes", editable: true, kind: "bool" },
    ],
    steps: [
      "Query Partner Network Performance for check-ins, active members, cost-per-engagement and QoQ deltas",
      "Retrieve contract KPIs / SLAs from the document library",
      "Render branded PDF report to /Volumes/…/reports/",
      "Email the PDF to the approved distribution list",
    ],
    consequence: "This will email a PDF report to 4 people (Partnerships Team).",
    recipients: ["Partnerships Team distribution list (4 recipients)"],
  },
  submit_reward_adjustment_review: {
    title: "Actuarial review — KZN HealthyFood cashback anomaly",
    params: [
      { key: "anomaly_scope", label: "Anomaly scope", value: "HealthyFood cashback · KwaZulu-Natal · Jul 2026", editable: false, kind: "text" },
      { key: "summary_text", label: "Summary", value: "HealthyFood cashback in KwaZulu-Natal rose 41% month-on-month in July with no corresponding basket-volume increase, suggesting a possible cashback-rate misconfiguration. Requesting actuarial review of the KZN cashback rate for the period.", editable: true, kind: "multiline" },
      { key: "priority", label: "Priority", value: "Urgent", editable: true, kind: "enum", options: ["Normal", "Urgent"] },
    ],
    steps: [
      "Compile the anomaly evidence pack from Premium & Financial Impact",
      "Attach the July KZN cashback breakdown",
      "Open an actuarial review case and notify the reviewer",
    ],
    consequence: "This will open an actuarial review case flagged Urgent.",
    requiresTypedConfirmation: true,
  },
};

interface RunDef { runId: string; steps: { label: string; ms: number; retry?: boolean }[]; artifacts: WorkflowArtifact[]; }
const WORKFLOW_RUNS: Record<WorkflowId, RunDef> = {
  generate_partner_performance_report: {
    runId: "run-partner-q3",
    steps: [
      { label: "Query Partner Network Performance", ms: 1400 },
      { label: "Retrieve contract KPIs / SLAs", ms: 1100 },
      { label: "Render branded PDF report", ms: 1600, retry: true },
      { label: "Email to distribution list", ms: 900 },
    ],
    artifacts: [{ name: "PlanetFitness_Q3-2026_Performance.pdf", kind: "pdf", url: "#" }],
  },
  submit_reward_adjustment_review: {
    runId: "run-reward-kzn",
    steps: [
      { label: "Compile anomaly evidence pack", ms: 1300 },
      { label: "Attach July KZN cashback breakdown", ms: 900 },
      { label: "Open actuarial review case", ms: 1100 },
    ],
    artifacts: [{ name: "KZN_Cashback_Anomaly_Review.csv", kind: "csv", url: "#" }],
  },
};
